openapi: 3.0.0
info:
  title: Project Ecommerce API
  version: 1.0.0
  description: |
    Tài liệu API cho hệ thống Ecommerce.
    - Được xây dựng bằng Laravel.
    - Sử dụng JWT cho xác thực.
servers:
  - url: http://localhost/api/v1

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id: { type: integer }
        name: { type: string }
        email: { type: string }
        created_at: { type: string, format: date-time }
        updated_at: { type: string, format: date-time }
    UserProfile:
      type: object
      properties:
        id: { type: integer }
        user_id: { type: integer }
        avatar: { type: string, format: uri }
        phone: { type: string, format: phone }
        birthdate: { type: string, format: date }
        gender: { type: string}
        address: { type: string }
        created_at: { type: string, format: date-time }
        updated_at: { type: string, format: date-time }
    UserProfileResource:
      type: object
      properties:
        id:
          type: integer
          example: 1
        user_id:
          type: integer
          example: 1
        full_name:
          type: string
          example: "Nguyen Van A"
        phone:
          type: string
          example: "0123456789"
        address:
          type: string
          example: "123 Đường ABC, Quận 1, TP.HCM"

    Product:
      type: object
      properties:
        id: { type: integer }
        name: { type: string }
        price: { type: number, format: float }
        description: { type: string }
        images:
          type: array
          items: { type: string, format: uri }
        created_at: { type: string, format: date-time }
        updated_at: { type: string, format: date-time }

    Order:
      type: object
      properties:
        id: { type: integer }
        user_id: { type: integer }
        total: { type: number, format: float }
        status: { type: string }
        created_at: { type: string, format: date-time }
        updated_at: { type: string, format: date-time }

paths:
  /auth/register:
    post:
      summary: Đăng ký tài khoản mới
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                email: { type: string, format: email }
                password: { type: string, format: password }
              required: [name, email, password]
      responses:
        '201':
          description: Đăng ký thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Lỗi dữ liệu đầu vào
  /auth/login:
    post:
      summary: Đăng nhập
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string, format: email }
                password: { type: string, format: password }
              required: [email, password]
      responses:
        '200':
          description: Đăng nhập thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token: { type: string }
                  token_type: { type: string }
        '401':
          description: Sai thông tin đăng nhập
  /customer/user-profile:
    get:
      summary: Lấy thông tin user
      tags: [Customer]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Thông tin user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Chưa xác thực
  /shop/products:
    get:
      summary: Lấy danh sách sản phẩm
      tags: [Shop]
      parameters:
        - in: query
          name: page
          schema: { type: integer }
          description: Trang hiện tại
        - in: query
          name: per_page
          schema: { type: integer }
          description: Số lượng mỗi trang
      responses:
        '200':
          description: Danh sách sản phẩm
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  meta:
                    type: object
                    properties:
                      current_page: { type: integer }
                      last_page: { type: integer }
                      total: { type: integer }
  /customer/orders:
    post:
      summary: Đặt hàng
      tags: [Customer]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      product_id: { type: integer }
                      quantity: { type: integer }
              required: [items]
      responses:
        '201':
          description: Đặt hàng thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Lỗi dữ liệu đầu vào
        '401':
          description: Chưa xác thực
